# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff3906e228f795784f89310f3f1e06049b25beb143f229a2877ecd9041a9478c8360f6634b7f1f6755c76bbe3aaeba626360dffe1609a81967709f909d58809a

test:
  secret_key_base: c19eb2e2b7d5a82dd0f69c24981fbb0ffddb4d5edd4fdc12009b405f305b9d4a8f36ddc1fee80ace3da8c914f32092e029982f921e092041de5b016aad21f107

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
